# Introduction {#intro}

The Labor Force Survey (LFS) started in the spring of 2005 (1384 in Persian calendar) to achieve seasonal and annual labor force indicators and their changes in the country and the province levels. Prior to that, the statistical needs of the country's human resource sector were met by demographic statistical projects of the Statistical Center of Iran and sampling projects of the Ministry of Labor and Social Affairs, the most important of which are:

*   Sample population census, Statistical Center of Iran, 1968 : 
*   Human Resource Census, Ministry of labor and social affairs, 1969-1972
*   Urban and Rural Population Census, Statistical Center of Iran, 1971
*   Employment and Unemployment Statistics in Tehran, Statistical Center of Iran , 1979
*   Plan to Review General issues of Human Resource and Employment, Ministry of labor and social affairs, 1982
*   Social and Economic Characteristics Census Plan, 1987-1989 and 1992-1995
*   Population and Housing Census, Statistical Center of Iran, 1956,1966,1976,1986
*   Survey of Household Employment and Unemployment Characteristics, Statistical Center of Iran, 1997-2004

The labor force Survey data has been designed and implemented using the recommendations of the International Labor Organization (ILO), And therefore, the results will be a more reliable basis for determining the country's position among other countries in the world. It is the main source of key labor market indicators in Iran.

In this document, we explain the cleaning steps needed prior to use of the LFS data. But before that, it is necessary to have a brief overview of the general information on the labor force survey. Detailed information is available in reports of Statistical Center of Iran (Link). 

The rest of this document is organized as follows. In section 2, we take a look at the design of survey and definitions used in it. In section 3, we briefly review the two survey questionnaires. Section 4 explains the cleaning procedure step by step, and finally, in section 5, we provide some descriptive statistics and plots of main labor market indicators in Iran.

This document is free to read, If you are using any material of this document, please cite it as :

* Naser Amanzadeh, Ali Naghizadeh (2021) \textit{“Iran Labor Force Survey: Introduction and Data Cleaning”}

You can find R codes [Here](https://github.com/TeIAS-LFS/Iran-Labor-Force-Survey/tree/master/R%20Codes) and necessary files for cleaning like _Meta Data_, _LFS_colnames_, etc [Here](https://github.com/TeIAS-LFS/Iran-Labor-Force-Survey/tree/master/Files)

